In [1]:
%matplotlib inline

In [2]:
from keras.models import Sequential
from keras.layers import Conv2D, ZeroPadding2D
import cv2
import numpy as np
from numpy import genfromtxt
import pandas as pd

w1 = '/Users/victor_sy_wang/Developer/ML/openface/models/openface/layer1_w.csv'
b1 = '/Users/victor_sy_wang/Developer/ML/openface/models/openface/layer1_b.csv'

Using TensorFlow backend.


In [20]:
layer1_w = genfromtxt(w1, delimiter=',', dtype=None)
layer1_w = layer1_w.reshape(64, 3, 7, 7)
layer1_w = np.transpose(layer1_w, (2, 3, 1, 0))
layer1_b = genfromtxt(b1, delimiter=',', dtype=None)
# print(layer1_w.shape)
# print(layer1_b)
layer1 = [layer1_w, layer1_b]
print(layer1[0].shape, layer1[1].shape, layer1[1])

((7, 7, 3, 64), (64,), array([ 0.07432853, -0.06500489,  0.01973198, -0.03164541,  0.04986416,
        0.04746565, -0.06268317,  0.04497291, -0.05216052, -0.06176173,
        0.02636961, -0.03982262, -0.06870739, -0.01500778,  0.00372739,
       -0.07971381, -0.06127921,  0.04724471, -0.03808348, -0.03344806,
        0.07216649,  0.07477196,  0.0629585 ,  0.05848179,  0.03575065,
       -0.03879078, -0.01604805, -0.07423716, -0.00941265,  0.0214014 ,
       -0.02287229,  0.0663086 , -0.01010718, -0.02637136, -0.00139301,
       -0.01988044, -0.05324499, -0.07041611, -0.06099652, -0.06074483,
       -0.00696069,  0.07159741, -0.07825537, -0.033103  , -0.00622472,
       -0.07154575, -0.04059464,  0.00037237, -0.00041962,  0.07437113,
       -0.0089185 , -0.04167552, -0.01440586, -0.00870561, -0.05802949,
        0.05733399, -0.02441243,  0.05660551,  0.04555712,  0.05215101,
        0.0126888 ,  0.0545151 ,  0.021539  , -0.02868187]))


In [21]:
model = Sequential()
model.add(ZeroPadding2D(padding=(3, 3), input_shape=(96, 96, 3)))
model.add(Conv2D(64, (7, 7), strides=(2, 2)))

model.layers[1].set_weights(layer1)

In [22]:
w= model.layers[1].get_weights()
print(w[0].shape, w[1])

((7, 7, 3, 64), array([ 0.07432853, -0.06500489,  0.01973198, -0.03164541,  0.04986416,
        0.04746565, -0.06268317,  0.04497291, -0.05216052, -0.06176173,
        0.02636961, -0.03982262, -0.06870739, -0.01500778,  0.00372739,
       -0.07971381, -0.06127921,  0.04724471, -0.03808348, -0.03344806,
        0.07216649,  0.07477196,  0.0629585 ,  0.05848179,  0.03575065,
       -0.03879078, -0.01604805, -0.07423716, -0.00941265,  0.0214014 ,
       -0.02287229,  0.0663086 , -0.01010718, -0.02637136, -0.00139301,
       -0.01988044, -0.05324499, -0.07041611, -0.06099652, -0.06074483,
       -0.00696069,  0.07159741, -0.07825537, -0.033103  , -0.00622472,
       -0.07154575, -0.04059464,  0.00037237, -0.00041962,  0.07437113,
       -0.0089185 , -0.04167552, -0.01440586, -0.00870561, -0.05802949,
        0.05733399, -0.02441243,  0.05660551,  0.04555712,  0.05215101,
        0.0126888 ,  0.0545151 ,  0.021539  , -0.02868187], dtype=float32))


In [26]:
img = cv2.imread('/Users/victor_sy_wang/Developer/ML/openface/images/examples-aligned/lennon-1.png', 1)
img = img[...,::-1]
img2 = np.transpose(img, (2,0,1)) 
print img.shape
# print img2.shape
cv2.imshow('img', img)
# cv2.imshow('img2', img2)
# cv2.waitKey(5000)
# cv2.destroyAllWindows()

[[[49 38 39]
  [48 39 42]
  [43 34 34]
  ..., 
  [54 41 43]
  [53 39 41]
  [46 34 36]]

 [[40 29 34]
  [35 24 28]
  [39 28 32]
  ..., 
  [47 35 39]
  [50 38 42]
  [53 42 46]]

 [[43 33 33]
  [39 28 32]
  [44 33 37]
  ..., 
  [43 32 38]
  [39 28 36]
  [40 30 36]]

 ..., 
 [[18 17 23]
  [18 17 23]
  [18 16 22]
  ..., 
  [22 21 26]
  [23 22 28]
  [21 20 26]]

 [[19 18 24]
  [18 17 23]
  [21 16 23]
  ..., 
  [21 20 25]
  [19 18 24]
  [22 21 27]]

 [[19 18 24]
  [18 17 23]
  [19 16 23]
  ..., 
  [21 20 26]
  [21 20 26]
  [19 18 24]]]


In [25]:
img = cv2.imread('/Users/victor_sy_wang/Developer/ML/openface/images/examples-aligned/lennon-1.png', 1)
x_train = np.array([img])
y = model.predict_on_batch(x_train)
print(x_train.shape)
print(y.shape)
print(y[:, :, :, 1].shape)
print(y[:, :, :, 1])



(1, 96, 96, 3)
(1, 48, 48, 64)
(1, 48, 48)
[[[ 178.89474487  295.9914856   341.25442505 ...,  396.10992432
    383.29675293  267.45471191]
  [  38.23655319   97.11819458  121.54769897 ...,  148.10423279
    150.06465149  122.79751587]
  [ -47.35509109  -45.11118698  -60.07111359 ...,  -38.27817154
    -40.02341843   -7.02156115]
  ..., 
  [ -18.17034149    1.40752602    7.63542986 ...,    8.53856945
    -10.73673534   -2.1843276 ]
  [  -6.98798895   15.44428349   22.24919891 ...,  -19.76063728
    -26.02472878  -13.98241711]
  [-109.96028137 -144.59524536 -167.74571228 ..., -205.91598511
   -204.01652527 -134.10224915]]]
